---
Author: Tímea Moder
Version: 198 17-CNL 113 588, Rev. A
Date: 2012-06-14

---
= The Real Time Streaming Protocol (RTSP) Protocol Modules for TTCN-3 Toolset with TITAN, User Guide
:author: Tímea Moder
:revnumber: 198 17-CNL 113 588, Rev. A
:revdate: 2012-06-14
:toc:

== About This Document

=== How to Read This Document

This is the User Guide for the Real Time Streaming Protocol (RTSP) protocol module. The Real Time Streaming Protocol (RTSP) protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with  Function Specification <<_3, [3]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language <<_1, ‎[1]>> is essential. Basic knowledge of the RTSP <<_5, [5]>> protocol is valuable when reading this document.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor version R8B (1.8.pl1) or higher installed. For installation guide see <<_2, [2]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R8B.

= Protocol Modules

== Overview

Protocol modules implement the message structure of the related protocol in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language <<_1, [1]>> and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

== Installation

The set of protocol modules can be used for developing TTCN-3 test suites using any text editor. However, to make the work more efficient a TTCN-3- enabled text editor is recommended (e.g. `nedit`, `xemacs`). Since the RTSP protocol is used as a part of a TTCN-3 test suite, this requires Titan TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<_2, [2]>>.

== Configuration

== Module Parameters

[[tsp-rtsp-encdec-debugging]]
=== `tsp_RTSP_EncDec_debugging`

There is a boolean module parameter for debugging purposes of encode/decode functions:

Its default value is `_false_`, thus in order to have debug information about encoding and decoding it must be set to `_true_` in the test suite configuration file in the `[MODULE_PARAMETERS]` section.

[[tsp-crlf-mode]]
=== tsp_crlf_mode

There is a module parameter `tsp_crlf_mode` of type `strict_crlf_mode` which defined as follows:

[source]
type enumerated strict_crlf_mode {ERROR, WARNING, WARNING_ONCE, ACCEPT};

This module parameter is introduced to control the reaction of the decoder for the missing "\r". In RTSP (and in HTTP 1.0) each line shall be finished by a sequence of "\r\n". If only a "\n" has been found, the decoder can report and return according to the following table:

[cols=",,",options="header",]
|======================================================================
|Tsp_crlf_value |Decoder returns with |Log report
|`ERROR` |`BUFFER_FAIL` |
|`WARNING` |/no interruption/ |Missing "\r".
|`WARNING_ONCE` |/no interruption/ |Missing "\r" at first occurrence
|`ACCEPT` |/no interruption/ |/no report/
|======================================================================

= Examples

The "demo" directory of the deliverable contains the following additional files:

* __RTSP_Demo.prj__ (for `mctr_gui`) – project file of the demo application
* `modify_Makefile` – an example script, it does the needed modifications in the _Makefile_ automatically
* __RTSP_Demo.cfg__ – configuration file for the demo
* __RTSP_Demo.ttcn__ - contains simple examples of a server and a client, use templates (which are in the file __RTSP_Templates.ttcn__) to create messages easily, use the encoding/decoding function to encode/decode the RTSP PDUs.
* __RTSP_Templates.ttcn__ – contains example templates
*_Makefile_ – In order to compile the RTSP protocol module you can use the _Makefile_ generated by the TTCN-3 compiler using the given TTCN-3 files. The example _Makefile_ in the demo directory assumes use of IPL4 Test Port
* A symbolic link was created to all necessary files

= Terminology

No specific terminology is used.

= Abbreviations

TTCN-3:: Testing and Test Control Notation version 3

RTSP:: Real Time Streaming Protocol

= References

[[_1]]
[1] ETSI ES 201 873-1 v.3.2.1 (02/2007) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_2]]
[2] User Documentation for the TITAN TTCN-3 Test Executor

[[_3]]
[3] The Real Time Streaming Protocol (RTSP) Protocol Modules for TTCN-3 Toolset with TITAN, Function Specification

[[_4]]
[4] Programmer’s Technical Reference for TITAN TTCN-3 Test Executor

[[_5]]
[5] IETF https://www.ietf.org/rfc/rfc2326.txt[RFC 2326] +
Real Time Streaming Protocol (RTSP)
